### PR TITLE
Update readme/classifiers

### PR DESCRIPTION
**Pull request by jburel**
Clarify change in the url if installed with version prior to 5.2.6
This will require a version bump since the clarification should be pushed to pypi

Added classifiers to `setup.py`

### CODE REVIEW

**Comment by will-moore** [comment]
Good to merge

**Comment by jburel** [comment]
https://testpypi.python.org/pypi?:action=display&name=omero-weberror&version=0.2.1

**Comment by aleksandra-tarkowska** [comment]
looks good

```
(omerovenv) MacBookPro:OMERO.py ola$ pip install -i https://testpypi.python.org/pypi omero-weberror
Collecting omero-weberror
  Downloading https://testpypi.python.org/packages/94/d4/c9620ca06691a26097641782ffbd879d017e279fab7e143be147f45a159d/omero-weberror-0.2.1.tar.gz
Building wheels for collected packages: omero-weberror
  Running setup.py bdist_wheel for omero-weberror ... done
  Stored in directory: /Users/ola/Library/Caches/pip/wheels/c5/42/85/c7f6289df0201557fe8d2a0763812932281abfb34a02ddaa59
Successfully built omero-weberror
Installing collected packages: omero-weberror
Successfully installed omero-weberror-0.2.1
```

**Comment by aleksandra-tarkowska** [comment]
@jburel could you release please

**Comment by jburel** [comment]
https://pypi.python.org/pypi?:action=display&name=omero-weberror&version=0.2.1

and
https://github.com/openmicroscopy/omero-weberror/tree/v0.2.1

**Pull request merged**
